package cz.aaa.unit2026.tracking

import kotlinx.coroutines.flow.StateFlow

/**
 * Platform-agnostic interface for a connected tracking client.
 *
 * All state mutations ([startSession], [stopSession]) update [sessionState] immediately,
 * even while offline — the UI never blocks on connectivity.
 *
 * JVM implementation (Android + Desktop): [SupabaseTrackingClient].
 */
interface TrackingClient {

    /** Live view of the current session. Null = no active session. Works offline. */
    val sessionState: StateFlow<TrackingSession?>

    /** Whether the client currently has a live server connection. */
    val isConnected: StateFlow<Boolean>

    /**
     * The account this device is currently synced to, or null before the first successful
     * connect (or on platforms without a sync backend). Devices that share an account see
     * the same [sessionState]. Changes after a successful [redeemLinkingCode].
     */
    val accountId: StateFlow<String?>

    /**
     * Starts the connection loop: connects, then reconnects on failure with exponential backoff.
     * Suspends until [disconnect] is called. Launch in a long-lived coroutine scope.
     */
    suspend fun run(deviceId: String)

    /**
     * Starts a focus session. Updates [sessionState] immediately (works offline).
     * If connected, sends the start command to the server so other clients are notified.
     * On next reconnect, any offline-started session is pushed to the server automatically.
     */
    suspend fun startSession(startedAtMs: Long, targetEndAtMs: Long)

    /**
     * Stops the active session early. Updates [sessionState] immediately (works offline).
     * If connected, sends the stop command so other clients are notified.
     */
    suspend fun stopSession()

    /**
     * Pauses the active session. Updates [sessionState] immediately (works offline).
     * No-op if there is no active session or the session is already paused.
     * If connected, broadcasts the pause to other clients.
     */
    suspend fun pauseSession()

    /**
     * Resumes a paused session. Updates [sessionState] immediately (works offline).
     * No-op if there is no active session or the session is not paused.
     * If connected, broadcasts the resume to other clients.
     */
    suspend fun resumeSession()

    /** Terminates the connection loop and closes any open WebSocket. */
    fun disconnect()

    /**
     * Generates a short-lived linking code tied to the current account that another
     * device can redeem to join this account. Codes expire after a few minutes.
     * Throws [UnsupportedOperationException] on backends without a sync server.
     */
    suspend fun createLinkingCode(): String

    /**
     * Redeems a linking code generated by another device. On success, this device leaves
     * its current account (which is deleted if empty) and joins the target account.
     * Returns the new [accountId]. The current Realtime subscription is torn down and
     * re-established on the new account.
     * Throws on invalid/expired codes or on backends without a sync server.
     */
    suspend fun redeemLinkingCode(code: String): String
}
