import java.util.Properties
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidLibrary)
    alias(libs.plugins.kotlinSerialization)
}

// Reads supabase.url / supabase.anonKey from root local.properties and emits
// an internal `SupabaseConfig` object into commonMain. Values are baked into
// the artifact at build time; local.properties is gitignored so credentials
// never land in the repo. The anon/publishable key is client-safe by design.
val generateSupabaseConfig = tasks.register("generateSupabaseConfig") {
    val localProps = rootProject.file("local.properties")
    val outputDir = layout.buildDirectory.dir("generated/supabase/kotlin")
    inputs.file(localProps).withPropertyName("localProperties")
    outputs.dir(outputDir).withPropertyName("outputDir")
    doLast {
        val props = Properties().apply {
            localProps.inputStream().use { load(it) }
        }
        val url = props.getProperty("supabase.url")
            ?: error("supabase.url missing from local.properties")
        val anonKey = props.getProperty("supabase.anonKey")
            ?: error("supabase.anonKey missing from local.properties")
        val pkgDir = outputDir.get().asFile.resolve("cz/aaa/unit2026")
        pkgDir.mkdirs()
        pkgDir.resolve("SupabaseConfig.kt").writeText(
            """
            |// Generated by :shared:generateSupabaseConfig — DO NOT EDIT.
            |// Sourced from local.properties (gitignored).
            |package cz.aaa.unit2026
            |
            |internal object SupabaseConfig {
            |    const val URL = "$url"
            |    const val ANON_KEY = "$anonKey"
            |}
            |
            """.trimMargin()
        )
    }
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    jvm()

    js {
        browser()
    }

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
    }

    sourceSets {
        val androidJvmMain by creating {
            dependsOn(commonMain.get())
            dependencies {
                implementation(libs.ktor.clientCore)
                implementation(libs.ktor.clientCio)
                implementation(libs.ktor.clientContentNeg)
                implementation(libs.ktor.serializationJson)
                implementation(libs.supabase.auth)
                implementation(libs.supabase.postgrest)
                implementation(libs.supabase.realtime)
            }
        }
        androidMain.get().dependsOn(androidJvmMain)
        jvmMain.get().dependsOn(androidJvmMain)
        commonMain.get().kotlin.srcDir(generateSupabaseConfig)
        commonMain.dependencies {
            implementation(libs.kotlinx.coroutinesCore)
            implementation(libs.kotlinx.serialization.json)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
    }
}

android {
    namespace = "cz.aaa.unit2026.shared"
    compileSdk = libs.versions.android.compileSdk.get().toInt()
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    defaultConfig {
        minSdk = libs.versions.android.minSdk.get().toInt()
    }
}
